Pharmacogenetics.Website/Areas/TranslatorManagement/Controllers/TranslatorController.cs
using Pharmacogenetics.Business.AppServices;
using Pharmacogenetics.Business.Interfaces;
using Pharmacogenetics.Website.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using Pharmacogenetics.Helper;
using Pharmacogenetics.Website.Bases;
using Pharmacogenetics.Models.ViewModels;

namespace Pharmacogenetics.Website.Areas.TranslatorManagement.Controllers
{
    public class TranslatorController : MvcController
    {
        // GET: TranslatorManagement/Translator
        public ActionResult Index()
        {
            return View();
        }

        //public ActionResult UploadTranslatorData()
        //{
        //    TranslatorDataViewModel TranslatorDataViewModel = new TranslatorDataViewModel();
        //    return View(TranslatorDataViewModel);
        //}
        public ActionResult UploadTranslatorData()
        { 
            return View();
        }

        [HttpPost]
        public JsonResult UploadTranslatorDataJson()
        {
            try
            {
                if (Request.Files.Count > 0)
                {
                    var file = Request.Files[0];

                    if (file != null && file.ContentLength > 0)
                    {


                        var uploadDir = "~/uploads";
                        if (!Directory.Exists(Server.MapPath(uploadDir)))
                            Directory.CreateDirectory(Server.MapPath(uploadDir));
                        var filePath = Path.Combine(Server.MapPath(uploadDir), file.FileName);
                        var fileUrl = Path.Combine(uploadDir, file.FileName);
                        file.SaveAs(filePath);


                        var  newFileName = "Bi-Allele" + DateTime.Now.ToFileTime() + ".csv";
                        var newFilePathAndName = Path.Combine(Server.MapPath(uploadDir), newFileName);


                        System.IO.File.Move(filePath, newFilePathAndName);

                        string uploadStatusKey = Guid.NewGuid().ToString();
                        HttpContext ctx = System.Web.HttpContext.Current;
                        List<string> status = new List<string>();
                        new Thread(() =>
                        {
                            System.Web.HttpContext.Current = ctx;

                          //  PatientTranslatorService patientTranslatorService = new PatientTranslatorService();
                          //bool  operationStatus = patientTranslatorService.ExecuteComparing(status, ctx, uploadStatusKey);

                            //TranslatorManager translatorManager = new TranslatorManager();
                            //translatorManager.ProcessFile(newFilePathAndName, uploadStatusKey, ctx, null, ref status);

                        }).Start();
                        return Json(new { newFilePathAndName, uploadStatusKey }, JsonRequestBehavior.AllowGet);
                    }
                }
            }
            catch (Exception)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Upload failed");
            }
            return Json("File uploaded successfully");
        }

        [HttpPost]



        [HttpGet]
        public JsonResult UploadTranslatorDataStatusJson(string id)
        {
                List<string> status = new List<string>();
                List<string> logStatus = new List<string>();
            try
            {
                log.Info(DateTime.Now + " UploadTranslatorDataStatusJson");
                if (System.Web.HttpContext.Current.Application["listStatus" + id] != null)
                {
                    status = (List<string>)System.Web.HttpContext.Current.Application["listStatus" + id];
                }
                if (System.Web.HttpContext.Current.Application["listStatusInner" + id] != null)
                {
                    logStatus = (List<string>)System.Web.HttpContext.Current.Application["listStatusInner" + id];
                }
            }
            catch (Exception)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(null, JsonRequestBehavior.AllowGet);
            }
            return Json(new { breifStatus = status, logStatus = logStatus }, JsonRequestBehavior.AllowGet);
        }



        #region Translator Output

        TranslatorAppService tAS = new TranslatorAppService();

        public ActionResult TranslatorOutput(string projectId)
        {
            List<SelectItemViewModel> projectsList = tAS.GetAllProjects();
            projectsList.Insert(0, new SelectItemViewModel() { key = "0", value = "All" });
            ViewBag.ProjectsList = projectsList;
            List<SelectItemViewModel> genesList = tAS.GetAllGenes();
            genesList.Insert(0, new SelectItemViewModel() { key = "0", value = "All" });
            ViewBag.GenesList = genesList;
            List<SelectItemViewModel> allelesList = tAS.GetAllSingleAlleles();
            allelesList.Insert(0, new SelectItemViewModel() { key = "All", value = "All" });
            ViewBag.AllelesList = allelesList;
            ViewBag.ProjectsListSelectedItem = projectId;
            List<TranslatorGeneAlleleViewModel> genesAlleles = null;
            if (projectId != null)
            {
                int projectIdInteger = 0;
                int.TryParse(projectId, out projectIdInteger);
                genesAlleles = tAS.GetGenesAndAlleles(
                    new List<int>() { projectIdInteger }, null, null, null);
            }
            ViewBag.GenesAlleles = genesAlleles;
            return View();
        }

        public ActionResult FilterByGeneAndAllele(List<string> ddlProjectId, List<string> ddlGeneId, List<string> ddlAllele1Id, List<string> ddlAllele2Id)
        {
            List<int> projectIdList = ddlProjectId != null ? ddlProjectId.Select(i => Convert.ToInt32(i)).ToList() : null;
            List<int> geneIdList = ddlGeneId != null ? ddlGeneId.Select(i => Convert.ToInt32(i)).ToList() : null;
            List<TranslatorGeneAlleleViewModel> genesAlleles = null;
            if (ddlProjectId != null || ddlGeneId != null || ddlAllele1Id != null || ddlAllele2Id != null)
            {
                genesAlleles = tAS.GetGenesAndAlleles(projectIdList, geneIdList, ddlAllele1Id, ddlAllele2Id);
            }
            return PartialView("TranslatorGeneAlleleGridPartial", genesAlleles);
        }

        [HttpPost]
        public ActionResult ShowAssaysAndCallsOfTranslator(int projectId, int geneId,int alleleId)
        {
            List<AssayCallViewModel> assaysAndCalls = tAS.GetAssaysAndCalls(projectId,geneId,alleleId);
            return PartialView("TranslatorAssayCallGridPartial", assaysAndCalls);
        }
        public ActionResult ExportTranslatorGenesAllelesToExcel()
        {
            List<TranslatorGeneAlleleViewModel> listGeneAllele = (List<TranslatorGeneAlleleViewModel>)TempData["TranslatorListGeneAllele"];
            if (listGeneAllele != null)
            {
                DataTable dt = new DataTable();
                dt.Columns.Add("Project Name", typeof(string));
                dt.Columns.Add("Gene", typeof(string));
                dt.Columns.Add("Allele", typeof(string));

                if (listGeneAllele != null)
                {
                    foreach (TranslatorGeneAlleleViewModel geneAllele in listGeneAllele)
                    {
                        dt.Rows.Add(geneAllele.projectName, geneAllele.geneName, geneAllele.alleleName);
                    }
                }
                ExportFile.ExportToFileCSV("TranslatorsGeneAllele", dt, Response);
            }
            return PartialView("TranslatorGeneAlleleGridPartial", listGeneAllele);
        }

        public ActionResult ExportTranslatorGeneAssaysCallsToExcel(string projectId, string geneId,string alleleId)
        {
            int projectIdNum;
            int.TryParse(projectId, out projectIdNum);
            int geneIdNum;
            int.TryParse(geneId, out geneIdNum);
            int alleleIdNum;
            int.TryParse(alleleId, out alleleIdNum);
            List<AssayCallViewModel> listAssayCall = null;
            if (projectIdNum != 0 && geneIdNum != 0)
            {
                listAssayCall = tAS.GetAssaysAndCalls(projectIdNum, geneIdNum, alleleIdNum);
                DataTable dt = new DataTable();
                dt.Columns.Add("Assay", typeof(string));
                dt.Columns.Add("RsId", typeof(string));
                dt.Columns.Add("Call", typeof(string));
                if (listAssayCall != null)
                {
                    foreach (AssayCallViewModel gene in listAssayCall)
                    {
                        dt.Rows.Add(gene.assayName, gene.rsId, gene.callName);
                    }
                }
                ExportFile.ExportToFileCSV("GeneAssaysCalls", dt, Response);
            }
            return PartialView("TranslatorAssayCallGridPartial", listAssayCall);
        }

        #endregion



        #region Translator Methods
        #endregion

    }
}

Pharmacogenetics.Website/Areas/TranslatorManagement/Views/Translator/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section banner{
    <div class="container-fluid">
        <div class="row">
            <div class="banner">
                <div class="caption-banner">
                    <h1>Pharmacogenomics</h1>
                    <p>Is the study of how genes affect a person's response to drugs. This relatively new field combines pharmacology (the science of drugs) and genomics (the study of genes and their functions) to develop effective, safe medications and doses that will be tailored to a person's genetic makeup.</p>
                    <a href="#" class="btn btn-start">Get started</a>
                </div>
            </div>
        </div>
    </div>
}

Pharmacogenetics.Website/Areas/TranslatorManagement/Views/Translator/TranslatorAssayCallGridPartial.cshtml
@model List<Pharmacogenetics.Models.ViewModels.AssayCallViewModel>


@if (Model != null && Model.Count != 0)
{
    <table class="table table-bordered cell-border table-striped table-r">
        <thead>
        <tr>
            <th>Assay</th>
            <th>RsId</th>
            <th>Call</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var assayCall in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => assayCall.assayName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => assayCall.rsId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => assayCall.callName)
                </td>
            </tr>
        }
        </tbody>
    </table>

    <a id="excel" href="#" class="btn btn-primary" onclick="postDataProjectGene()">Export</a>
}
else
{
    <br/>
    <h4 style="text-align: center;">No Data Found</h4>
}

<script>
    function postDataProjectGene() {
        var projectId = $("#modalProjectId").val();
        var geneId = $("#modalGeneId").val();
        var alleleId = $("#modalAlleleId").val();
        location.href = '@Url.Action("ExportTranslatorGeneAssaysCallsToExcel","Translator")' + '?projectId=' + projectId + '&geneId=' + geneId + '&alleleId='+alleleId;
    }
</script>

Pharmacogenetics.Website/Areas/TranslatorManagement/Views/Translator/TranslatorGeneAlleleGridPartial.cshtml
@using Pharmacogenetics.Models.ViewModels
@model List<TranslatorGeneAlleleViewModel>

@if (Model != null && Model.Count != 0)
{
    <div class="tablePatients project-list-container">
        <table id="tableGeneAlleleInner" class="table table-bordered cell-border table-striped table-r">
            <thead class="thead-inverse">
                <tr>
                    <th>Project Name</th>
                    <th>Gene</th>
                    <th>Allele</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                @foreach (var geneAllele in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => geneAllele.projectName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => geneAllele.geneName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => geneAllele.alleleName)
                        </td>
                        <td>
                            @Ajax.ActionLink(" ", "ShowAssaysAndCallsOfTranslator", "Translator", new { ProjectId = @geneAllele.projectId, geneId = @geneAllele.geneId, alleleId = @geneAllele.alleleId }, new AjaxOptions { UpdateTargetId = "tableAssaysCalls", HttpMethod = "POST", InsertionMode = InsertionMode.Replace, OnBegin = "startLoading('ajaxBusy2')", OnComplete = "stopLoading('ajaxBusy2');" }, new { @onclick = "modalTitleAndData('" + @geneAllele.geneName + "' , '" + @geneAllele.alleleName + "','" + @geneAllele.projectId + "','" + @geneAllele.geneId + "','" + @geneAllele.alleleId + "');", @class = "btn btn-primary fa fa-eye", data_toggle = "modal", data_target = "#divModal" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="row btn-export-output">
        <a id="excel" href="@Url.Action("ExportTranslatorGenesAllelesToExcel","Translator")" class="btn btn-primary" onclick="reSubmitForm();@{ TempData["TranslatorListGeneAllele"] = Model; }">Export</a>
    </div>
        <div id="divModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content project-list-container">
                    <div class="modal-header">
                        <button id="close-btn" type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 id="modalTitle" class="modal-title"></h4>
                    </div>
                    <div class="modal-body project-list-container">
                        <div id="ajaxBusy2" style="display: inline-block; position: absolute;padding-left: 38%">
                            <p>
                                <img src="../../Content/themes/base/images/ring-alt.gif" alt="Loading..." />
                            </p>
                        </div>
                        <input id="modalProjectId" type="hidden" />
                        <input id="modalGeneId" type="hidden" />
                        <input id="modalAlleleId" type="hidden" />
                        <div id="tableAssaysCalls">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        }
        else if (Model != null && Model.Count == 0)
        {
        <div class="tablePatients">
            <table id="tableGeneAlleleInner" class="cell-border table-striped table-r">
                <thead class="thead-inverse">
                    <tr>
                        <th>Project Name</th>
                        <th>Gene</th>
                        <th>Allele</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
        }


        <script>
            function modalTitleAndData(geneName,alleleName, projectId,geneId,alleleId) {
                $("#modalTitle").text("Gene Name: " + geneName + " , Allele Name: " + alleleName);
                $("#modalProjectId").val(projectId);
                $("#modalGeneId").val(geneId);
                $("#modalAlleleId").val(alleleId);
            }

            //$(document).ready(function()
            //{
            //    $('.modal').on('hidden.bs.modal', function(e)
            //    {
            //        $("#tableAssaysCalls").empty();
            //    }) ;
            //});


            $(document).ready(function () {
                $('.modal').on('hidden.bs.modal',
                    function (e) {
                        $("#tableAssaysCalls").empty();
                    });
                $('.modal').on('shown.bs.modal',
                    function (e) {
                        $('.modal-body').scrollTop(0);
                    });
            });


            function reSubmitForm() {
                var form = $('#form0');
                form.submit();
                $link = $('#excel');
                location.href = $link.attr('href');
            }
        </script>

        <style>
            .modal-body {
                min-height: 170px;
                max-height: calc(100vh - 200px);
                overflow-y: auto;
            }
        </style>

Pharmacogenetics.Website/Areas/TranslatorManagement/Views/Translator/TranslatorOutput.cshtml
@using Microsoft.Owin.Security.Notifications
@using Pharmacogenetics.Models.ViewModels
@model List<Pharmacogenetics.Models.ViewModels.TranslatorGeneAlleleViewModel>
@{
    ViewBag.Title = "Home Page";
}


<div class="wraper-main-container">

    <div class="wraper-inner-container">

        <div class="row">
            <h1>Translator Output</h1>
            @*<h3>Filter By</h3>*@
        </div>
        <div class="row">

            @using (Ajax.BeginForm("FilterByGeneAndAllele", "Translator", new AjaxOptions {UpdateTargetId = "tableGeneAllele", HttpMethod = "POST", InsertionMode = InsertionMode.Replace, OnBegin = "startLoading('ajaxBusy1')", OnComplete = "divDataTable();stopLoading('ajaxBusy1');"}))
    {
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">

                @Html.Label("Project", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.ListBox("ddlProjectId", new SelectList(ViewBag.ProjectsList, "key", "value", ViewBag.ProjectsListSelectedItem), new {name = "ddlProjectId", @onchange = "$(this.form).submit();", @class = "selectAuto form-control"})
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.Label("Gene", htmlAttributes: new { @class = "control-label col-md-2" })
                                @Html.ListBox("ddlGeneId", new SelectList(ViewBag.GenesList, "key", "value"), new {name = "ddlGeneId", @onchange = "$(this.form).submit();", @class = "selectAuto form-control"})
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                @*<h4>Allele 1</h4>*@

                @Html.Label("Allele 1", htmlAttributes: new { @class = "control-label col-md-12" })


                @Html.ListBox("ddlAllele1Id", new SelectList(ViewBag.AllelesList, "key", "value"), new {name = "ddlAllele1Id", @onchange = "$(this.form).submit();", @class = "selectAuto form-control"})
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                @*<h4>Allele 2</h4>*@

                @Html.Label("Allele 2", htmlAttributes: new { @class = "control-label col-md-12" })
                @Html.ListBox("ddlAllele2Id", new SelectList(ViewBag.AllelesList, "key", "value"), new {name = "ddlAllele2Id", @onchange = "$(this.form).submit();", @class = "selectAuto form-control"})
            </div>
        </div>
    </div>
    }
        </div>
        <div class="row">


            <div>

                <div id="tableGeneAllele">
                    @Html.Partial("TranslatorGeneAlleleGridPartial", (List<TranslatorGeneAlleleViewModel>)ViewBag.GenesAlleles)
                </div>
                <div id="ajaxBusy1" style="position: absolute;left: 50%; top: 50%;display:none">
                    <p>
                        <img src="../../Content/themes/base/images/ring-alt.gif" alt="Loading..." />
                    </p>
                </div>
            </div>


            </div>



    </div>
</div>


<script>
    function divDataTable() {
        $('#tableGeneAlleleInner').dataTable({
            retrieve: true,
            columnDefs: [
                { type: 'allele-text-numeric', targets: 2 },
                { "targets": 3, "orderable": false }
            ]
        });
    }
</script>

Pharmacogenetics.Website/Areas/TranslatorManagement/Views/Translator/UploadTranslatorData.cshtml
@model Pharmacogenetics.Website.Models.ViewModels.TranslatorDataViewModel

@{
    ViewBag.Title = "Upload Translator Data";
}

<div class="col-md-6 col-md-offset-3">

    <div class="uploader">
        @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", id = "frmUploadTranslatorFile", @action = "" }))
        {
            @Html.AntiForgeryToken()
            @Html.TextBoxFor(model => model.FileUpload, new { type = "file", data_val = "true", data_val_required = "The FileUpload field is required." })
            @Html.ValidationMessageFor(model => model.FileUpload)

            <input value="Upload" class="btn btn-primary upload" type="submit">
        }

    </div>
</div>

<br />
<div id="messageParsing">

</div>


<div id="detialsDivMessage" style="display:none">
    @*<button data-toggle="collapse" data-target="#demo">Details</button>*@

    <div id="demo" class="collapse">
        <div id="messageInnerParsing">

        </div>
    </div>
</div>




@section scripts{
    <script type="text/javascript">
        var actionUpload = '@Url.Action("UploadTranslatorDataJson", "Translator")';
        var actionUploadStatus = '@Url.Action("UploadTranslatorDataStatusJson", "Translator")';
        var imageUploadPath = '@Url.Content("~/Content/themes/phrma/imgs/fileuploader-dragdrop-icon.png")';
        var flagStatusShow = false;
        var idleInterval = null;
        var dataFile = null;

        $(document).ready(function () {
            // enable fileuploader plugin
            $('input[name="FileUpload"]').fileuploader({
                changeInput: '<div class="fileuploader-input">' +
                                  '<div class="fileuploader-input-inner">' +
                                      '<img src="' + imageUploadPath + '">' +
                                      '<h3 class="fileuploader-input-caption"><span>Drag and drop files here</span></h3>' +
                                      '<p>or</p>' +
                                      '<div class="fileuploader-input-button"><span>Browse Files</span></div>' +
                                  '</div>' +
                              '</div>',
                theme: 'dragdrop',
                extensions: ['txt', 'csv', 'xls', 'xlsx'],
                upload: {
                    //url: 'php/ajax_upload_file.php',
                    data: null,
                    type: 'POST',
                    enctype: 'multipart/form-data',
                    start: true,
                    synchron: true,
                    beforeSend: null,
                    onSuccess: function (result, item) {
                        var data = JSON.parse(result);

                        // if success
                        if (data.isSuccess && data.files[0]) {
                            item.name = data.files[0].name;
                        }

                        // if warnings
                        if (data.hasWarnings) {
                            for (var warning in data.warnings) {
                                alert(data.warnings);
                            }

                            item.html.removeClass('upload-successful').addClass('upload-failed');
                            // go out from success function by calling onError function
                            // in this case we have a animation there
                            // you can also response in PHP with 404
                            return this.onError ? this.onError(item) : null;
                        }

                        item.html.find('.column-actions').append('<a class="fileuploader-action fileuploader-action-remove fileuploader-action-success" title="Remove"><i></i></a>');
                        setTimeout(function () {
                            item.html.find('.progress-bar2').fadeOut(400);
                        }, 400);
                    },
                    onError: function (item) {
                        var progressBar = item.html.find('.progress-bar2');

                        if (progressBar.length > 0) {
                            progressBar.find('span').html(0 + "%");
                            progressBar.find('.fileuploader-progressbar .bar').width(0 + "%");
                            item.html.find('.progress-bar2').fadeOut(400);
                        }

                        item.upload.status != 'cancelled' && item.html.find('.fileuploader-action-retry').length == 0 ? item.html.find('.column-actions').prepend(
                            '<a class="fileuploader-action fileuploader-action-retry" title="Retry"><i></i></a>'
                        ) : null;
                    },
                    onProgress: function (data, item) {
                        debugger;
                        dataFile = item.file;
                        var progressBar = item.html.find('.progress-bar2');

                        if (progressBar.length > 0) {
                            progressBar.show();
                            progressBar.find('span').html(data.percentage + "%");
                            progressBar.find('.fileuploader-progressbar .bar').width(data.percentage + "%");
                        }
                    },
                    onComplete: null,
                },
                onRemove: function (item) {
                    //$.post('./php/ajax_remove_file.php', {
                    //    file: item.name
                    //});
                },
                captions: {
                    feedback: 'Drag and drop files here',
                    feedback2: 'Drag and drop files here',
                    drop: 'Drag and drop files here'
                },
            });

        });

        $("#frmUploadTranslatorFile").submit(function (e) {
            debugger;
            e.preventDefault();
            //var fileInput = document.getElementById('FileUpload');
            //var files = fileInput.files;

            var data = new FormData();
            data.append("file" + 0, dataFile);

            $.ajax({
                type: "POST",
                url: actionUpload,
                contentType: false,
                processData: false,
                data: data,
                async: true,
                success: function (result) {

                    //flagStatusShow = false;
                    flagStatusShow = true;
                    idleInterval = setInterval(function () { timerIncrement(result.uploadStatusKey); }, 1000); // 1 minute
                    console.log(result);
                },
                error: function (xhr, status, p3, p4) {
                    flagStatusShow = false;
                    var err = "Error " + " " + status + " " + p3 + " " + p4;
                    if (xhr.responseText && xhr.responseText[0] == "{")
                        err = JSON.parse(xhr.responseText).Message;
                    console.log(err);
                }
            });

        });


        function timerIncrement(uploadStatusKey) {
            //debugger;
            $.ajax({
                type: "GET",
                url: actionUploadStatus + "/" + uploadStatusKey,
                contentType: false,
                processData: false,
                data: uploadStatusKey,
                //async: true,
                success: function (result) {
                    if (flagStatusShow) {
                        $("#messageParsing").html(result.breifStatus.join("<br />"));
                        console.log(result);
                        if (result.breifStatus[result.breifStatus.length - 1] == "Complete") {
                            clearInterval(idleInterval);
                            flagStatusShow = false;
                            $("#detialsDivMessage").show();
                            $("#messageInnerParsing").html(result.logStatus.join("<br />"));
                        }
                    }
                },
                error: function (xhr, status, p3, p4) {
                    var err = "Error " + " " + status + " " + p3 + " " + p4;
                    if (xhr.responseText && xhr.responseText[0] == "{")
                        err = JSON.parse(xhr.responseText).Message;
                    console.log(err);
                }
            });
        }
    </script>
}