Pharmacogenetics.Website/Areas/ProjectManagement/Controllers/ProjectController.cs
using Pharmacogenetics.Business.AppServices;
using System.Collections.Generic;
using System.Web.Mvc;
using Pharmacogenetics.Website.Bases;
using Pharmacogenetics.Models.ViewModels;
using System;
using System.Net;
using System.IO;
using System.Threading;
using System.Web;
using System.Linq;
using Pharmacogenetics.BaseClasses.Enums;
using Pharmacogenetics.Website.Areas.TranslatorManagement;


namespace Pharmacogenetics.Website.Areas.ProjectManagement.Controllers
{
    public class ProjectController : MvcController
    {
        // GET: ProjectManagement/Patient
        public ActionResult Index()
        {
            return View();
        }



        #region Project Page

        ProjectAppService pAS = new ProjectAppService();
        public ActionResult ProjectPage()
        {
            List<ProjectViewModel> projectsList = pAS.GetAllProjects();
            return View(projectsList);
        }



        #endregion

        [HttpGet]
        public ActionResult Create()
        {
            ProjectViewModel model = new ProjectViewModel();
            return View();
        }
        [HttpPost]
        public ActionResult Create(ProjectViewModel model)
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];
                if (file != null && file.ContentLength > 0)
                {

                }
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult CreateJson(ProjectViewModel model)
        {
            List<string> status = new List<string>();
            //to make unique id for each operation (each session)
            string uploadStatusKey = Guid.NewGuid().ToString();
            try
            {
                bool translatorFileUploadFlag = false;
                bool patientFileUploadFlag = false;
                bool filesUploadFlag = false;
                //check if the request contain any files
                if (Request.Files.Count > 0)
                {
                    ProjectAppService projectAppService = new ProjectAppService();
                    model.File = new List<FileViewModel>();

                    int j = 0;
                    //loop for each file
                    foreach (string fileTypeName in Request.Files.AllKeys)
                    {
                        var file = Request.Files[j];
                        //check if the size of file is valid
                        if (file != null && file.ContentLength > 0)
                        {
                            //set upload path
                            var uploadDir = "~/uploads";
                            //check if the path is exist else create it
                            if (!Directory.Exists(Server.MapPath(uploadDir)))
                                Directory.CreateDirectory(Server.MapPath(uploadDir));
                            //create file and concatinate the unique id with it's name
                            var filePath = Path.Combine(Server.MapPath(uploadDir), "Project-" + uploadStatusKey + "-" + file.FileName);
                            //var fileUrl = Path.Combine(uploadDir, file.FileName);
                            file.SaveAs(filePath);


                            //check the type of the file
                            if (CommonEnums.ProjectFilesEnums.fileTranslator.ToString().Equals(fileTypeName))
                            {
                                model.File.Add(new FileViewModel()
                                {
                                    FilePath = filePath,
                                    FileType = (byte)CommonEnums.ProjectFilesEnums.fileTranslator,
                                });
                                //flag to make sure at least one translator file is uploaded
                                translatorFileUploadFlag = true;
                            }
                            if (CommonEnums.ProjectFilesEnums.filePatient.ToString().Equals(fileTypeName))
                            {
                                model.File.Add(new FileViewModel()
                                {
                                    FilePath = filePath,
                                    FileType = (byte)CommonEnums.ProjectFilesEnums.filePatient,
                                });
                                //flag to make sure at least one paitent file is uploaded
                                patientFileUploadFlag = true;
                            }
                            if (CommonEnums.ProjectFilesEnums.fileCopyNumber.ToString().Equals(fileTypeName))
                            {
                                model.File.Add(new FileViewModel()
                                {
                                    FilePath = filePath,
                                    FileType = (byte)CommonEnums.ProjectFilesEnums.fileCopyNumber,
                                });
                            }
                        }
                        j++;
                    }

                    #region translator upload (Khaled section)
                    var filePathTranslatorList = model.File.Where(x => x.FileType == (byte)CommonEnums.ProjectFilesEnums.fileTranslator).Select(x => x.FilePath).ToList();

                    int i = 0;
                    foreach (var fileTranslator in filePathTranslatorList)
                    {
                        Random rand = new Random();
                        
                        string filePathTranslator = fileTranslator;//model.File.Where(x => x.FileType == (byte)CommonEnums.ProjectFilesEnums.fileTranslator).Select(x => x.FilePath).FirstOrDefault();

                        var uploadDirectory = "~/uploads";
                        var fileparts = filePathTranslator.Split('.');
                        var extension = fileparts[fileparts.Length - 1];


                        string newFileName = "";
                        string newFilePathAndName = "";

                        do
                        {
                            newFileName = "Bi-Allele" + DateTime.Now.ToFileTime() + rand.Next() + "." + extension;
                            newFilePathAndName = Path.Combine(System.Web.HttpContext.Current.Server.MapPath(uploadDirectory), newFileName);
                        }
                        while (System.IO.File.Exists(newFilePathAndName));

                        //var newFileName = "Bi-Allele" + DateTime.Now.ToFileTime() + rand.Next() + "." + extension;
                        //var newFilePathAndName = Path.Combine(System.Web.HttpContext.Current.Server.MapPath(uploadDirectory), newFileName);


                        System.IO.File.Move(filePathTranslator, newFilePathAndName);

                        model.File.Where(f => f.FileType == (byte)CommonEnums.ProjectFilesEnums.fileTranslator).ToList()[i].FilePath = newFilePathAndName;

                        //(fu => fu.FilePath = newFilePathAndName);
                        i++;
                    }
                    #endregion

                    //calculate the final flag flag to make sure at least one paitent and one translator file is uploaded
                    filesUploadFlag = translatorFileUploadFlag && patientFileUploadFlag;
                    if (filesUploadFlag)
                    {
                        bool createProjectStatus = projectAppService.CreateProject(model);
                        //display in the log the status of project creation
                        if (createProjectStatus)
                            updateSessionStatus(status, "Project's Information Created successfully", uploadStatusKey);
                        if (createProjectStatus)
                        {
                            //cretae thread for parsing, analysis, comparing and storing the data
                            HttpContext ctx = System.Web.HttpContext.Current;
                            Thread t = new Thread(new ThreadStart(() =>
                            {
                                System.Web.HttpContext.Current = ctx;
                                ProcessFiles(model, uploadStatusKey, status);
                            }));
                            t.Start();
                        }
                        else
                            return Json(new { Status = CommonEnums.MessageTypeEnum.Error, uploadStatusKey = uploadStatusKey, Message = "Project create failed!" }, JsonRequestBehavior.AllowGet);
                    }
                    else
                        return Json(new { Status = CommonEnums.MessageTypeEnum.Error, uploadStatusKey = uploadStatusKey, Message = "Please upload valid Translator file and Patient file to create the project!" }, JsonRequestBehavior.AllowGet);
                    return Json(new { Status = CommonEnums.MessageTypeEnum.Success, uploadStatusKey = uploadStatusKey }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("No Files , Upload failed");
                }
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                updateSessionStatus(status, ex.Message, uploadStatusKey);
                updateSessionStatus(status, "Error", uploadStatusKey);
                return Json("Upload failed");
            }
            return Json("File uploaded successfully");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            ProjectAppService projectAppService = new ProjectAppService();
            ProjectViewModel model = projectAppService.GetProject(id);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(ProjectViewModel model)
        {
            return View(model);
        }

        public ActionResult EditJson(ProjectViewModel model)
        {

Pharmacogenetics.Website/Areas/ProjectManagement/Views/Project/Create.cshtml
@model Pharmacogenetics.Models.ViewModels.ProjectViewModel

@{
    ViewBag.Title = "Create Project";
}

<div class="wraper-main-container">
    <div class="wraper-inner-container">
        <h1 class="heading">@ViewBag.Title</h1>
        <div class="clear">&nbsp;</div>
        <div class="row">
            <div class="col-md-12">
                @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", id = "frmUploadProjectFiles" }))
                {
                    @Html.AntiForgeryToken()

                    @*<div class="form-horizontal">*@
                    
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="">
                                    @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group hide">
                                @Html.LabelFor(model => model.ProjectID, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="">
                                    @Html.EditorFor(model => model.ProjectID, new { htmlAttributes = new { @class = "form-control text-box single-line" } })
                                    @Html.ValidationMessageFor(model => model.ProjectID, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group hide">
                                @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CreateDate, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ProjectDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="">
                                    @Html.TextAreaFor(model => model.ProjectDescription, new { @class = "form-control", @cols = 80, @rows = 10 })
                                    @Html.ValidationMessageFor(model => model.ProjectDescription, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ProjectNotes, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="">
                                    @Html.TextAreaFor(model => model.ProjectNotes, new { @class = "form-control", @cols = 80, @rows = 10 })
                                    @Html.ValidationMessageFor(model => model.ProjectNotes, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group hide">
                        @Html.LabelFor(model => model.DeleteStatus, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DeleteStatus, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DeleteStatus, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group hide">
                        @Html.LabelFor(model => model.ModifyDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ModifyDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ModifyDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group hide">
                        @Html.LabelFor(model => model.DeleteDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DeleteDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DeleteDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row upload-s">
                        <div class="col-md-4 divFileTranslator">
                            @Html.TextBox("File", null, new { @id = "fileTranslator", type = "file", data_val = "true", data_val_required = "The FileUpload field is required." })
                        </div>
                        <div class="col-md-4 divFilePatient">
                            @Html.TextBox("File", null, new { @id = "filePatient", type = "file", data_val = "true", data_val_required = "The FileUpload field is required." })
                        </div>
                        <div class="col-md-4 divFileCopyNumber">
                            @Html.TextBox("File", null, new { @id = "fileCopyNumber", type = "file", data_val = "true", data_val_required = "The FileUpload field is required." })
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="submit" value="Create" class="btn btn-block btn-primary upload" id="btnCreateProject" />
                        </div>
                    </div>
                    @*</div>*@
                }
            </div>
        </div>
        <div id="messageParsing">
            <div id="ajaxBusy1" style="position: absolute;left: 50%; top: 50%;display:none">
                <p>
                    <img src="../../Content/themes/base/images/ring-alt.gif" alt="Loading..." />
                </p>
            </div>
        </div>


        <div id="detialsDivMessage" style="display:none">
            <button data-toggle="collapse" data-target="#demo">Details</button>

            <div id="demo" class="collapse">
                <div id="messageInnerParsing">

                </div>
            </div>
        </div>


    </div>
</div>

<style>
    /*
                .divFileTranslator .fileuploader-input {
                    background-color:#FAF7C5;
                }
                .divFilePatient .fileuploader-input {
                    background-color:#CBFAC5;
                }
                .divFileCopyNumber .fileuploader-input {
                    background-color:#C5FAF6;
                }
                */
</style>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        var actionUpload = '@Url.Action("CreateJson", "Project")';
        var actionUploadStatus = '@Url.Action("CreateStatusJson", "Project")';
        var imageUploadPath = '@Url.Content("~/Content/themes/phrma/imgs/fileuploader-dragdrop-icon.png")';
        var pageMode = "Create";

    </script>
    <script src="~/Scripts/App/Areas/ProjectManagement/Project/Index.js"></script>
}

Pharmacogenetics.Website/Areas/ProjectManagement/Views/Project/Edit.cshtml
@model Pharmacogenetics.Models.ViewModels.ProjectViewModel

@{
    ViewBag.Title = "Edit Project " + Model.ProjectName;
}


<div class="wraper-main-container">

    <div class="wraper-inner-container">



        <h1 class="heading">Edit @Model.ProjectName</h1>
        <div class="clear">&nbsp;</div>
        <div class="row">
            <div class="col-md-12">

                @using (Html.BeginForm("", "", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmUploadProjectFiles" }))
                {
                    @Html.AntiForgeryToken()

                    @*<div class="form-horizontal">*@

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="">
                                    @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group hide">
                                @Html.LabelFor(model => model.ProjectID, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="">
                                    @Html.EditorFor(model => model.ProjectID, new { htmlAttributes = new { @class = "form-control text-box single-line" } })
                                    @Html.ValidationMessageFor(model => model.ProjectID, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group hide">
                                @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CreateDate, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ProjectDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="">
                                    @Html.TextAreaFor(model => model.ProjectDescription, new { @class = "form-control", @cols = 80, @rows = 10 })
                                    @Html.ValidationMessageFor(model => model.ProjectDescription, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ProjectNotes, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="">
                                    @Html.TextAreaFor(model => model.ProjectNotes, new { @class = "form-control", @cols = 80, @rows = 10 })
                                    @Html.ValidationMessageFor(model => model.ProjectNotes, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group hide">
                        @Html.LabelFor(model => model.DeleteStatus, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DeleteStatus, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DeleteStatus, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group hide">
                        @Html.LabelFor(model => model.ModifyDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ModifyDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ModifyDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group hide">
                        @Html.LabelFor(model => model.DeleteDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DeleteDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DeleteDate, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="row upload-s">
                        @if (Model.File != null)
                        {
                            <div class="col-md-4">
                                @Html.Label("Translator Files")
                                    @foreach (var fileItem in Model.File.Where(x => x.FileType == (byte)Pharmacogenetics.BaseClasses.Enums.CommonEnums.ProjectFilesEnums.fileTranslator))
                                    {
                                        Html.RenderPartial("_fileItem", fileItem);
                                    }
                            </div>
                            <div class="col-md-4">
                                @Html.Label("Pateint Files")
                                    @foreach (var fileItem in Model.File.Where(x => x.FileType == (byte)Pharmacogenetics.BaseClasses.Enums.CommonEnums.ProjectFilesEnums.filePatient))
                                    {
                                        Html.RenderPartial("_fileItem", fileItem);
                                    }
                            </div>
                            <div class="col-md-4">
                                @Html.Label("Copy Number Files")
                                    @foreach (var fileItem in Model.File.Where(x => x.FileType == (byte)Pharmacogenetics.BaseClasses.Enums.CommonEnums.ProjectFilesEnums.fileCopyNumber))
                                    {
                                        Html.RenderPartial("_fileItem", fileItem);
                                    }
                            </div>
                        }
                    </div>


                    <div class="form-group">
                        <div class="col-md-offset-5 col-md-2">
                            <input type="submit" value="Edit" class="btn btn-primary upload" />
                        </div>
                    </div>
                    @*</div>*@
                }


            </div>
        </div>
        <div id="messageParsing">
            <div id="ajaxBusy1" style="position: absolute;left: 50%; top: 50%;display:none">
                <p>
                    <img src="../../Content/themes/base/images/ring-alt.gif" alt="Loading..." />
                </p>
            </div>
        </div>


        <div id="detialsDivMessage" style="display:none">
            <button data-toggle="collapse" data-target="#demo">Details</button>

            <div id="demo" class="collapse">
                <div id="messageInnerParsing">

                </div>
            </div>
        </div>


    </div>
</div>






<style>
    .divfileTranslator .fileuploader-input {
        background-color: #FAF7C5;
    }

    .divfilePatient .fileuploader-input {
        background-color: #CBFAC5;
    }

    .divfileCopyNumber .fileuploader-input {
        background-color: #C5FAF6;
    }
</style>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        var actionUpload = '@Url.Action("EditJson", "Project")';
        var actionUploadStatus = '@Url.Action("CreateStatusJson", "Project")';
        var imageUploadPath = '@Url.Content("~/Content/themes/phrma/imgs/fileuploader-dragdrop-icon.png")';
        var pageMode = "Edit";
    </script>
    <script src="~/Scripts/App/Areas/ProjectManagement/Project/Index.js"></script>
}

Pharmacogenetics.Website/Areas/ProjectManagement/Views/Project/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section banner{
    <div class="container-fluid">
        <div class="row">
            <div class="banner">
                <div class="caption-banner">
                    <h1>Pharmacogenomics</h1>
                    <p>Is the study of how genes affect a person's response to drugs. This relatively new field combines pharmacology (the science of drugs) and genomics (the study of genes and their functions) to develop effective, safe medications and doses that will be tailored to a person's genetic makeup.</p>
                    <a href="#" class="btn btn-start">Get started</a>
                </div>
            </div>
        </div>
    </div>
}

Pharmacogenetics.Website/Areas/ProjectManagement/Views/Project/_fileItem.cshtml
@model Pharmacogenetics.Models.ViewModels.FileViewModel
@{
    Pharmacogenetics.BaseClasses.Enums.CommonEnums.ProjectFilesEnums fileType = (Pharmacogenetics.BaseClasses.Enums.CommonEnums.ProjectFilesEnums)Model.FileType;
    string fileName = Path.GetFileName(Model.FilePath);
    //string fileServerPath = Server.MapPath(Model.FilePath);
    string fileServerPath = Url.Content("~/uploads/" + fileName);
}
<div class="col-md-12 @Html.Raw("div" + fileType)">
    @*@Html.TextBox("File", null, new { @id = fileType.ToString(), type = "file", data_val = "true", data_val_required = "The FileUpload field is required.", @multiple=false })*@
    <div class="fileuploader-items">
        <ul class="fileuploader-items-list">
            <li class="fileuploader-item file-type-application file-ext-csv upload-successful">
                <div class="columns">
                    <div class="column-thumbnail">
                        <div class="fileuploader-item-image fileupload-no-thumbnail">
                            <div style="background-color: #068120" class="fileuploader-item-icon"><i>csv</i></div>
                        </div>
                    </div>
                    <div class="column-title">
                        <div title="@fileName"><a href="@fileServerPath">@fileName <i class="fa fa-download" aria-hidden="true"></i></a></div>
                        @*<span>90.2 KB</span>*@
                    </div>
                    @*<div class="column-actions">
                        <a class="fileuploader-action fileuploader-action-remove" title="Remove"><i></i></a>
                     </div>*@
                </div>
                @*<div class="progress-bar2">
                        <div class="fileuploader-progressbar">
                            <div class="bar" style="width: 100%;"></div>
                        </div>
                        <span>100%</span>
                    </div>*@
            </li>
        </ul>
    </div>
</div>