Pharmacogenetics.Website/Areas/PatientManagement/Controllers/PatientController.cs
using Pharmacogenetics.Business.AppServices;
using Pharmacogenetics.Business.Interfaces;
using Pharmacogenetics.Website.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using Pharmacogenetics.Helper;
using Pharmacogenetics.Website.Bases;
using Pharmacogenetics.Models.ViewModels;

namespace Pharmacogenetics.Website.Areas.PatientManagement.Controllers
{
    public class PatientController : MvcController
    {
        // GET: PatientManagement/Patient
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult GetUsers(PatientViewModel model, int jtStartIndex = new int(), int jtPageSize = new int(), string jtSorting = null)
        {
            JsonResult returnedResult = Json(new { Result = "ERROR", Message = "Error" });
            int totalCount = new int();
            AppServiceManager appServiceManager = new AppServiceManager();
            //UserManagementAppService userAppService = new UserManagementAppService();
            var result = appServiceManager.PatientAppService.GetAllPatients(model, jtStartIndex, jtPageSize, jtSorting, out totalCount);
            returnedResult = Json(new { Result = "OK", Records = result, TotalRecordCount = totalCount });
            return returnedResult;
        }
        public ActionResult Insert()
        {
            var model = new PatientViewModel();
            return PartialView("_Add", model);
        }
        [HttpPost]
        public ActionResult Insert(PatientViewModel model)
        {
            return PartialView("_Add", model);
        }
        public ActionResult Update(int? id)
        {
            PatientAppService patientAppService = new PatientAppService();
            var model = patientAppService.GetPatient(id.Value);
            return PartialView("_Update", model);
        }
        [HttpPost]
        public ActionResult Update(PatientViewModel model)
        {
            PatientAppService patientAppService = new PatientAppService();
            //var model = userAppService.GetUser(model.Value);
            return PartialView("_Update", model);
        }
        public ActionResult UploadTrainData()
        {
            PatientTrainDataViewModel patientTrainDataViewModel = new PatientTrainDataViewModel();
            return View(patientTrainDataViewModel);
        }
        [HttpPost]
        public ActionResult UploadTrainData(PatientTrainDataViewModel model)
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    // var uploadDir = "~/uploads";
                    // if (!Directory.Exists(Server.MapPath(uploadDir)))
                    //     Directory.CreateDirectory(Server.MapPath(uploadDir));
                    // var filePath = Path.Combine(Server.MapPath(uploadDir), file.FileName);
                    // var fileUrl = Path.Combine(uploadDir, file.FileName);
                    // file.SaveAs(filePath);
                    // PatientAppService patientAppService = new PatientAppService();
                    // List<string> status = new List<string>();
                    // bool operationStatus = false;
                    // List<PatientResultViewModel> patientList = patientAppService.ParsePatientData(filePath, status, "");
                    // //patientAppService.StoreData(patientList, status, new List<string>(), "");
                    // int patientIter = 0;
                    // //foreach (var curPatient in patientList)
                    // //{
                    // //    patientIter++;
                    // //    //updateSessionStatus(status, string.Format("Check patient {0} {1}/{2} records", curPatient.PatientID, patientIter, patientList.Count));
                    // //    patientAppService.StorePatientData(curPatient, status,new List<string>(), "");
                    // //}
                    // operationStatus = true;
                    // if (operationStatus)
                    //     TempData["Success"] = string.Join("<br />", status);
                    // else
                    //     ViewData["Error"] = ViewData["Error"] + "\nError " + string.Join("<br />", status);
                    // 
                    // //var fileName = Path.GetFileName(file.FileName);
                    // //var path = Path.Combine(Server.MapPath("~/Images/"), fileName);
                    // //file.SaveAs(path);
                }
            }
            return View(model);
        }
        [HttpPost]
        public JsonResult UploadTrainDataJson()
        {
            try
            {
                if (Request.Files.Count > 0)
                {
                    var file = Request.Files[0];

                    if (file != null && file.ContentLength > 0)
                    {
                        var uploadDir = "~/uploads";
                        if (!Directory.Exists(Server.MapPath(uploadDir)))
                            Directory.CreateDirectory(Server.MapPath(uploadDir));
                        var filePath = Path.Combine(Server.MapPath(uploadDir), file.FileName);
                        var fileUrl = Path.Combine(uploadDir, file.FileName);
                        file.SaveAs(filePath);


                        string uploadStatusKey = Guid.NewGuid().ToString();

                        HttpContext ctx = System.Web.HttpContext.Current;
                        Thread t = new Thread(new ThreadStart(() =>
                        {
                            System.Web.HttpContext.Current = ctx;
                            ProcessFile(filePath, uploadStatusKey, ctx);
                        }));
                        t.Start();
                        //Thread thread = new Thread(() => ProcessFile(filePath, System.Web.HttpContext.Current));
                        //thread.Start();

                        //ProcessFile(filePath, uploadStatusKey, ctx);

                        //Thread newThread;
                        //newThread = new System.Threading.Thread(new ParameterizedThreadStart(ProcessFile));
                        //newThread.Start(filePath, System.Web.HttpContext.Current);
                        //
                        //Task.Run(() => ProcessFile(filePath, System.Web.HttpContext.Current));
                        return Json(new { filePath = filePath, uploadStatusKey = uploadStatusKey }, JsonRequestBehavior.AllowGet);


                        //
                        //var fileName = Path.GetFileName(file.FileName);
                        //var path = Path.Combine(Server.MapPath("~/Images/"), fileName);
                        //file.SaveAs(path);
                    }
                }
            }
            catch (Exception)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Upload failed");
            }
            return Json("File uploaded successfully");
        }
        [HttpPost]
        public JsonResult ProcessFile(string filePath, string uploadStatusKey, HttpContext ctx)
        {
            bool operationStatus = false;
            List<string> status = new List<string>();
            try
            {
                PatientAppService patientAppService = new PatientAppService();
                System.Web.HttpContext.Current.Application.Add("listStatus" + uploadStatusKey, new List<string>());

                List<PatientResultViewModel> patientList = patientAppService.ParsePatientData(filePath, status, uploadStatusKey);
                updateSessionStatus(status, "Analysis patients", ctx, uploadStatusKey);
                updateSessionStatus(status, "Analysis patients", ctx, uploadStatusKey);
                List<string> allStatusLog = new List<string>();
                List<string> statusLog = new List<string>();
                patientAppService.StoreData(patientList, statusLog, status, uploadStatusKey, new ProjectViewModel(), new Business.Containers.ProjectEntities());

                operationStatus = true;

                #region Execute Comparing
                if (operationStatus)
                {
                    PatientTranslatorService patientTranslatorService = new PatientTranslatorService();
                    //operationStatus = patientTranslatorService.ExecuteComparing(status, ctx, uploadStatusKey);
                }
                #endregion

                updateSessionStatus(status, string.Format("Complete"), ctx, uploadStatusKey);
                operationStatus = true;
            }
            catch (Exception ex)
            {
                updateSessionStatus(status, ex.Message, ctx, uploadStatusKey);
                updateSessionStatus(status, "Error", ctx, uploadStatusKey);
            }
            return Json(operationStatus, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult UploadTrainDataStatusJson(string id)
        {
            List<string> status = new List<string>();
            List<string> logStatus = new List<string>();
            try
            {
                log.Info(DateTime.Now + " UploadTrainDataStatusJson");
                if (System.Web.HttpContext.Current.Application["listStatus" + id] != null)
                {
                    status = (List<string>)System.Web.HttpContext.Current.Application["listStatus" + id];
                }
                if (System.Web.HttpContext.Current.Application["listStatusInner" + id] != null)
                {
                    logStatus = (List<string>)System.Web.HttpContext.Current.Application["listStatusInner" + id];
                }
            }
            catch (Exception)
            {

Pharmacogenetics.Website/Areas/PatientManagement/Views/Patient/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section banner{
    <div class="container-fluid">
        <div class="row">
            <div class="banner">
                <div class="caption-banner">
                    <h1>Pharmacogenomics</h1>
                    <p>Is the study of how genes affect a person's response to drugs. This relatively new field combines pharmacology (the science of drugs) and genomics (the study of genes and their functions) to develop effective, safe medications and doses that will be tailored to a person's genetic makeup.</p>
                    <a href="#" class="btn btn-start">Get started</a>
                </div>
            </div>
        </div>
    </div>
}

Pharmacogenetics.Website/Areas/PatientManagement/Views/Patient/PatientAssayCallGridPartial.cshtml
@model List<Pharmacogenetics.Models.ViewModels.AssayCallViewModel>
@if (Model != null && Model.Count != 0)
{






    <table class="table table-bordered cell-border table-striped table-r"   >
        <thead>
        <tr>
            <th>Assay</th>
            <th>RsId</th>
            <th>Call</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var assayCall in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => assayCall.assayName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => assayCall.rsId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => assayCall.callName)
                </td>
            </tr>
        }
        </tbody>
    </table>

    <a id="excel" href="#" onclick="postDataProjectPatientGene()" class="btn btn-primary">Export</a>
}
else
{
    <br/>
    <h4 style="text-align: center;">No Data Found</h4>
}



<script>
    function postDataProjectPatientGene() {
        var projectId = $("#modalProjectId").val();
        var patientId = $("#modalPatientId").val();
        var geneId = $("#modalGeneId").val();
        location.href = '@Url.Action("ExportPatientsGeneAssaysCallsToExcel", "Patient")' + '?projectId=' + projectId + '+&patientId=' + patientId + '&geneId=' + geneId;       
    }
</script>

Pharmacogenetics.Website/Areas/PatientManagement/Views/Patient/PatientGeneAlleleGridPartial.cshtml
@using Pharmacogenetics.Models.ViewModels
@model System.Collections.Generic.List<Pharmacogenetics.Models.ViewModels.PatientGeneAlleleViewModel>

@if (Model != null && Model.Count != 0)
{
    <div class="tablePatients project-list-container">
        <table id="tablePatientsInner" class="cell-border table-striped table-r">
            <thead class="thead-inverse">
                <tr>
                    <th>Project Name</th>
                    <th>Patient</th>
                    <th>Gene</th>
                    @*<th>Parent Gene</th>*@
                    <th>Allele</th>
                    <th>Copy Number</th>
                    <th>Probability</th>
                    <th></th>
                    <th>Recommendation</th>
                </tr>
            </thead>
            <tbody>

                @for (int i = 0; i < Model.Count; i++)
                {
                    for (int j = 0; j < Model[i].geneAllele.Count; j++)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => Model[i].geneAllele[j].projectName)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => Model[i].patientName)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => Model[i].geneAllele[j].geneName)
                            </td>
                            @*<td>
                                @Html.DisplayFor(modelItem => Model[i].geneAllele[j].parentGeneName)
                            </td>*@
                            <td>

                                @{
                        var al = Model[i].geneAllele[j].alleleName;
                        var list = Model[i].geneAllele[j].alleleName.Split(',');
                                }

                                @if (Model[i].geneAllele[j].probability)
                                {
                                    if (list.Length > 3)
                                    {
                                        al = "[" + list[0] + "," + list[1] + "," + list[2] + ",...]";
                                        @Html.DisplayFor(modelItem => al);
                                    <button type="button" onclick="alleleList('@Model[i].patientName', '@Model[i].geneAllele[j].geneName', '@Model[i].geneAllele[j].alleleName')" class="btn btn-primary" data-toggle="modal" data-target="#divModal">More Details</button>
                                    }
                                    else
                                    {
                                        al = "[" + al + "]";
                                        @Html.DisplayFor(modelItem => al);
                                    }
                                }
                                else
                                {
                                    if (list.Length > 3)
                                    {
                                        al = list[0] + "," + list[1] + "," + list[2] + ",...";
                                        @Html.DisplayFor(modelItem => al);
                                    <button type="button" onclick="alleleList('@Model[i].patientName', '@Model[i].geneAllele[j].geneName', '@Model[i].geneAllele[j].alleleName')" class="btn btn-primary" data-toggle="modal" data-target="#divModal">More Details</button>
                                    }
                                    else
                                    {
                                        @Html.DisplayFor(modelItem => al);
                                    }
                                }
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => Model[i].geneAllele[j].copyNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => Model[i].geneAllele[j].probability)
                            </td>
                            <td>
                                @Ajax.ActionLink(" ", "ShowAssaysAndCallsOfPatient", "Patient", new { projectId = @Model[i].geneAllele[j].projectId, patientId = @Model[i].patientId, geneId = @Model[i].geneAllele[j].geneId }, new AjaxOptions { UpdateTargetId = "tableAssaysCalls", HttpMethod = "POST", InsertionMode = InsertionMode.Replace, OnBegin = "startLoading('ajaxBusy2')", OnComplete = "stopLoading('ajaxBusy2');" }, new { @onclick = "modalTitleAndData('" + @Model[i].patientName + "' , '" + @Model[i].geneAllele[j].geneName + "','" + @Model[i].geneAllele[j].projectId + "','" + @Model[i].patientId + "','" + @Model[i].geneAllele[j].geneId + "');", @class = "btn btn-primary fa fa-eye", data_toggle = "modal", data_target = "#divModal" })
                            </td>

                            <td>
                                @Ajax.ActionLink(" ", "PatientGenoTypeRecommendation", "Patient", new { projectId = @Model[i].geneAllele[j].projectId, patientId = @Model[i].patientId, geneId = @Model[i].geneAllele[j].geneId }, new AjaxOptions { UpdateTargetId = "tableAssaysCalls", HttpMethod = "POST", InsertionMode = InsertionMode.Replace, OnBegin = "startLoading('ajaxBusy2')", OnComplete = "stopLoading('ajaxBusy2');" }, new { @onclick = "modalTitleAndData('" + @Model[i].patientName + "' , '" + @Model[i].geneAllele[j].geneName + "','" + @Model[i].geneAllele[j].projectId + "','" + @Model[i].patientId + "','" + @Model[i].geneAllele[j].geneId + "');", @class = "btn btn-primary fa fa-eye", data_toggle = "modal", data_target = "#divModal" })
                            </td>


                        </tr>
                    }
                }
            </tbody>
        </table>
      
    </div>

    <div class="row btn-export-output">
        <a id="excel" href="@Url.Action("ExportPatientsGenesAllelesToExcel", "Patient")" class="btn btn-primary" onclick="reSubmitForm();@{ TempData["PatientListGeneAllele"] = Model; }">Export</a>

    </div>

    <div id="divModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content project-list-container">
                <div class="modal-header">
                    <button id="close-btn" type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 id="modalTitle" class="modal-title"></h4>
                </div>
                <div class="modal-body project-list-container">
                    <div id="ajaxBusy2" style="display: inline-block; position: absolute; padding-left: 38%">
                        <p>
                            <img src="../../Content/themes/base/images/ring-alt.gif" alt="Loading..." />
                        </p>
                    </div>
                    <input id="modalProjectId" type="hidden" />
                    <input id="modalPatientId" type="hidden" />
                    <input id="modalGeneId" type="hidden" />
                    <div id="tableAssaysCalls">
                    </div>
                </div>
            </div>
        </div>
    </div>
    }
    else if (Model != null && Model.Count == 0)
    {
        <div class="tablePatients">
            <table id="tablePatientsInner" class="cell-border table-striped table-r">
                <thead class="thead-inverse">
                    <tr>
                        <th>Project Name</th>
                        <th>Patient</th>
                        <th>Gene</th>
                        @*<th>Parent Gene</th>*@
                        <th>Allele</th>
                        <th>Copy Number</th>
                        <th>Probability</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    }

    <script type="text/javascript">
        function modalTitleAndData(patientName, geneName, projectId, patientId, geneId) {
            $("#modalTitle").text("Patient Name: " + patientName + " , Gene Name: " + geneName);
            $("#modalProjectId").val(projectId);
            $("#modalPatientId").val(patientId);
            $("#modalGeneId").val(geneId);
        }

        $(document).ready(function() 
        {
            debugger;

            
            $('.modal').on('hidden.bs.modal',
                function(e) 
                {
                    $("#tableAssaysCalls").empty();
                });
            $('.modal').on('shown.bs.modal',
                function(e) {
                    $('.modal-body').scrollTop(0);
                });
        });

        function alleleList(patient, gene, alleles) 
        {
            var allelesList = alleles.split(',');
            window.startLoading('ajaxBusy2');
            var numberOfColumns = 3;
            var numberOfRows = Math.ceil(allelesList.length / 3);
            $("#modalTitle").text("Patient Name: " + patient + " , Gene Name: " + gene + " , Probability");
            var m = 0;
            var table = $('<table></table>').addClass('table table-bordered cell-border table-striped table-r');
            for (var i = 0; i < numberOfRows; i++) {
                var row = $('<tr></tr>');
                for (var j = 0; j < numberOfColumns; j++) {
                    var td;
                    if (m < allelesList.length) {
                        td = $('<td></td>').text(allelesList[m]);
                    } else {
                        td = $('<td></td>');
                    }
                    m++;
                    row.append(td);
                }
                table.append(row);
            }
            $('#tableAssaysCalls').append(table);
            window.stopLoading('ajaxBusy2');
        }

        function reSubmitForm() {
            var form = $('#form0');
            form.submit();
            $link = $('#excel');
            location.href = $link.attr('href');
        }
    </script>

<style>
    .modal-body {
        min-height: 170px;
        max-height: calc(100vh - 200px);
        overflow-y: auto;
    }
</style>

Pharmacogenetics.Website/Areas/PatientManagement/Views/Patient/PatientGeneAlleleGridPartialReport.cshtml
@model System.Collections.Generic.List<Pharmacogenetics.Models.ViewModels.PatientGeneAlleleViewModel>

@if (Model != null && Model.Count != 0)
{
    <div id="chartContainer" style="height: 300px; width: 100%;">
    </div>
    <div class="tablePatients">
        <table id="tablePatientsReportInner" class="cell-border table-striped">
            <thead class="thead-inverse">
            <tr>
                <th>Patient</th>
                <th>Number of Genes</th>
                <th>Number of Defined Alleles</th>
                <th>Number of Undefined Alleles</th>
            </tr>
            </thead>
            <tbody>

            @for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Model[i].patientName)
                    </td>

                    <td>
                        @Html.Raw(Model[i].geneAllele.Count)
                    </td>
                    <td>
                        @Html.Raw(Model[i].geneAllele.Count(x => x.alleleName != "UND" && x.alleleName != "-"))
                    </td>
                    <td>
                        @Html.Raw(Model[i].geneAllele.Count(x => x.alleleName == "UND" || x.alleleName == "-"))
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
    <a id="excel" href="@Url.Action("ExportReportToExcel", "Patient")" class="btn btn-primary" onclick="@{ TempData["ReportTableData"] = Model; }">Export</a>
}

Pharmacogenetics.Website/Areas/PatientManagement/Views/Patient/PatientOutput.cshtml
@using Microsoft.Owin.Security.Notifications
@using Pharmacogenetics.Models.ViewModels
@model List<Pharmacogenetics.Models.ViewModels.PatientGeneAlleleViewModel>
@{
    ViewBag.Title = "Home Page";
}



<div class="wraper-main-container">

    <div class="wraper-inner-container">


        <div class="row">
            <h1>Patient Output</h1>
            @*<h1>Filter By</h1>*@
        </div>
        <div class="row">
            @using (Ajax.BeginForm("FilterByPatientAndGene", "Patient", new AjaxOptions { UpdateTargetId = "tablePatients", HttpMethod = "POST", InsertionMode = InsertionMode.Replace, OnBegin = "startLoading('ajaxBusy1')", OnComplete = "divDataTable();stopLoading('ajaxBusy1');" }))
            {
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">


                            @Html.Label("Project", htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.ListBox("ddlProjectId", new SelectList(ViewBag.ProjectsList, "key", "value", ViewBag.ProjectsListSelectedItem), new { name = "ddlProjectId", @onchange = "$(this.form).submit();", @class = "selectAuto form-control" })
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">

                            @Html.Label("Patient", htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.ListBox("ddlPatientId", new SelectList(ViewBag.PatientsList, "key", "value"), new { name = "ddlPatientId", @onchange = "$(this.form).submit();", @class = "selectAuto form-control" })
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.Label("Gene", htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.ListBox("ddlGeneId", new SelectList(ViewBag.GenesList, "key", "value"), new { name = "ddlGeneId", @onchange = "$(this.form).submit();", @class = "selectAuto form-control" })
                        </div>
                    </div>
                </div>
                <div class="row">

                    <div class="col-md-4">
                        <div class="form-group">

                            @Html.Label("Allele 1", htmlAttributes: new { @class = "control-label col-md-12" })
                            @Html.ListBox("ddlAllele1Id", new SelectList(ViewBag.AllelesList, "key", "value"), new { name = "ddlAllele1Id", @onchange = "$(this.form).submit();", @class = "selectAuto form-control" })
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.Label("Allele 2", htmlAttributes: new { @class = "control-label col-md-12" })
                            @Html.ListBox("ddlAllele2Id", new SelectList(ViewBag.AllelesList, "key", "value"), new { name = "ddlAllele2Id", @onchange = "$(this.form).submit();", @class = "selectAuto form-control" })
                        </div>
                    </div>

                    <div class="col-md-4">
                        @Html.Label("Allele", htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="form-group col-md-6">
                            <h4>
                                @Html.CheckBox("cbAlleleUndefined", false, new { id = "cbAlleleUndefined", @checked = ViewBag.Undefined, name = "cbAlleleUndefined", @onchange = "dimAllelesList($(this.form))" })
                                Undefined
                            </h4>


                        </div>
                        <div class="form-group col-md-6">
                            <h4>
                                @Html.CheckBox("cbAlleleProbability", false, new { id = "cbAlleleProbability", @checked = ViewBag.Probability, name = "cbAlleleProbability", @onchange = "showAllelesList($(this.form))" })


                                Probability


                            </h4>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="row">


            <div>
                <div id="tablePatients">
                    <div class="clear">
                    </div>

                    @Html.Partial("PatientGeneAlleleGridPartial", (List<PatientGeneAlleleViewModel>)ViewBag.Patients)

                <div id="ajaxBusy1" style="position: absolute;left: 50%; top: 50%;display:none">
                    <p>
                        <img src="../../Content/themes/base/images/ring-alt.gif" alt="Loading..." />
                    </p>
                </div>
                </div>
            </div>
            </div>




    </div>
</div>


<script type="text/javascript">
    function divDataTable() {
        $('#tablePatientsInner').dataTable({
            retrieve: true,
            columnDefs: [
                { type: 'Alphanumeric', targets: 1 },
                { type: 'allele-text-numeric', targets: 3 },
                { type: 'checkbox', targets: 5 },
                { "targets": 6, "orderable": false }
            ]
        });
    }

    function dimAllelesList(form) {
        if ($('#cbAlleleUndefined').is(":checked")) {
            $('#ddlAllele1Id').val('').select2({
                placeholder: "-- Select --",
                allowClear: true
            });
            $('#ddlAllele2Id').val('').select2({
                placeholder: "-- Select --",
                allowClear: true
            });
            $('#ddlAllele1Id').prop('disabled', true);
            $('#ddlAllele2Id').prop('disabled', true);
            $('#cbAlleleProbability').prop('checked', false);
        } else {
            $('#ddlAllele1Id').prop('disabled', null);
            $('#ddlAllele2Id').prop('disabled', null);
        }
        form.submit();
    }

    function showAllelesList(form) {
        if ($('#cbAlleleProbability').is(":checked")) {
            $('#ddlAllele1Id').prop('disabled', null);
            $('#ddlAllele2Id').prop('disabled', null);
            $('#cbAlleleUndefined').prop('checked', false);
        }
        form.submit();
    }

</script>